name: Test and Approval Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [approval_received]
  
jobs:
  build-and-test-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean install

      - name: Run Cucumber Tests (DEV)
        run: mvn test -Dcucumber.filter.tags="@DEV"

      - name: Generate Test Coverage Report
        run: mvn jacoco:report

      - name: Clean Previous Reports
        run: rm -rf coverage-reports/*

      - name: Generate Visual Report with Coverage Metrics
        run: mvn jacoco:report && mvn site

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload Coverage Report to AWS S3
        run: aws s3 cp target/site/jacoco/ s3://${{ secrets.AWS_S3_BUCKET }}/extent-reports/

      - name: Summarize Coverage in Pull Request
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Test Coverage Summary:**
            - Coverage report has been generated and uploaded.
            - View the full report [here](https://s3.console.aws.amazon.com/s3/buckets/${{ secrets.AWS_S3_BUCKET }}/extent-reports/)
            - Review coverage changes to ensure adequate test coverage.

      - name: Archive Reports (DEV)
        uses: actions/upload-artifact@v4
        with:
          name: dev-test-reports
          path: |
            reports/
            reports/screenshots/

      - name: Send Approval Email (DEV)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          subject: "Approval Required: DEV Test Results"
          body: |
            Test reports for DEV environment are available.
            Please review and approve it.
          to: "sankarviswanathan1991@gmail.com"
          attachments: |
            reports/extent-report.html
            reports/screenshots/*

  wait-for-approval-dev:
    needs: build-and-test-dev
    uses: ./.github/workflows/reusable_approval.yml
    with:
      env_name: "DEV"

  build-and-test-sit:
    needs: wait-for-approval-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean install

      - name: Run Cucumber Tests (SIT)
        run: mvn test -Dcucumber.filter.tags="@SIT"

      - name: Generate Test Coverage Report
        run: mvn jacoco:report

      - name: Clean Previous Reports
        run: rm -rf coverage-reports/*

      - name: Generate Visual Report with Coverage Metrics
        run: mvn jacoco:report && mvn site

      - name: Upload Coverage Report to AWS S3
        run: aws s3 cp target/site/jacoco/ s3://${{ secrets.AWS_S3_BUCKET }}/extent-reports/

      - name: Summarize Coverage in Pull Request
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            **SIT Test Coverage Summary:**
            - Coverage report has been generated and uploaded.
            - View the full report [here](https://s3.console.aws.amazon.com/s3/buckets/${{ secrets.AWS_S3_BUCKET }}/extent-reports/)
            - Review coverage changes to ensure adequate test coverage.

      - name: Archive Reports (SIT)
        uses: actions/upload-artifact@v4
        with:
          name: sit-test-reports
          path: |
            reports/
            reports/screenshots/

      - name: Send Approval Email (SIT)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          subject: "Approval Required: SIT Test Results"
          body: |
            Test reports for SIT environment are available.
            Please review and approve it.
          to: "sankarviswanathan1991@gmail.com"
          attachments: |
            reports/extent-report.html
            reports/screenshots/*

  wait-for-approval-sit:
    needs: build-and-test-sit
    uses: ./.github/workflows/reusable_approval.yml
    with:
      env_name: "SIT"
